"""
File analyzer utility for test generation.

Finds the most suitable source file to generate tests for when a repository
has no test suite. Strategy:

  1. Check for known entry-point filenames first (main.py, index.ts, etc.)
  2. Fall back to the largest non-test source file under ``max_lines``.
  3. Automatically skip build artifacts, test files, generated code, and
     config-only files that have no testable logic.
"""
from __future__ import annotations

import logging
import os
from pathlib import Path

logger = logging.getLogger("komosis.utils.file_analyzer")

# Directories that contain no user-authored source code worth testing.
_SKIP_DIRS: frozenset[str] = frozenset({
    "node_modules", ".git", ".venv", "venv", "__pycache__",
    ".mypy_cache", ".pytest_cache", ".tox",
    "build", "dist", ".next", "out", "coverage",
    ".gradle", "target",          # Java/Kotlin build output
    "vendor",                     # Go / PHP dependency cache
    "Pods",                       # iOS CocoaPods
})

# File/path fragments that indicate a test file — skip when looking for source.
_TEST_MARKERS: tuple[str, ...] = (
    "test", "spec", "__test__", "_test.", "tests/", "specs/",
    ".test.", ".spec.",
)

# Config/meta files that have no testable logic of their own.
_CONFIG_ONLY_FILES: frozenset[str] = frozenset({
    "setup.py", "setup.cfg", "pyproject.toml",
    "package.json", "tsconfig.json", "jest.config.js", "jest.config.ts",
    "vitest.config.ts", "vite.config.ts", "webpack.config.js",
    "babel.config.js", ".eslintrc.js", ".eslintrc.json",
    "rollup.config.js", "prettier.config.js",
    "Makefile", "Dockerfile", "docker-compose.yml",
    "go.mod", "go.sum",
    "pom.xml", "build.gradle", "settings.gradle",
    "Cargo.toml", "Cargo.lock",
    "Gemfile", "Gemfile.lock",
    "composer.json", "composer.lock",
    "mix.exs",
})

# Language → list of likely entry-point filenames (checked in order).
_ENTRY_SIGNALS: dict[str, list[str]] = {
    "python":     ["main.py", "app.py", "api.py", "server.py", "core.py",
                   "cli.py", "run.py", "manage.py"],
    "javascript": ["index.js", "app.js", "server.js", "main.js",
                   "api.js", "cli.js"],
    "typescript": ["index.ts", "app.ts", "server.ts", "main.ts",
                   "api.ts", "cli.ts"],
    "go":         ["main.go"],
    "java":       ["Main.java", "App.java", "Application.java",
                   "SpringBootApplication.java"],
    "kotlin":     ["Main.kt", "App.kt", "Application.kt"],
    "ruby":       ["app.rb", "main.rb", "server.rb", "application.rb"],
    "rust":       ["main.rs", "lib.rs"],
    "csharp":     ["Program.cs", "Startup.cs", "App.cs"],
    "php":        ["index.php", "app.php", "bootstrap.php"],
    "elixir":     ["lib/application.ex", "lib/router.ex"],
}

# Language → source file extensions (anything else is skipped).
_LANG_EXTENSIONS: dict[str, frozenset[str]] = {
    "python":     frozenset({".py"}),
    "javascript": frozenset({".js", ".mjs", ".cjs"}),
    "typescript": frozenset({".ts", ".tsx"}),
    "go":         frozenset({".go"}),
    "java":       frozenset({".java"}),
    "kotlin":     frozenset({".kt"}),
    "ruby":       frozenset({".rb"}),
    "rust":       frozenset({".rs"}),
    "csharp":     frozenset({".cs"}),
    "php":        frozenset({".php"}),
    "elixir":     frozenset({".ex", ".exs"}),
}


def _is_test_file(rel_path: str) -> bool:
    """Return True if the relative path looks like a test file."""
    lower = rel_path.lower()
    return any(marker in lower for marker in _TEST_MARKERS)


def _is_generated(content: str) -> bool:
    """Heuristic: skip files that appear auto-generated."""
    first_lines = content[:500].lower()
    return any(marker in first_lines for marker in (
        "generated by", "do not edit", "auto-generated", "this file is autogenerated",
    ))


def find_best_file_to_test(
    workspace_dir: str,
    language: str,
    *,
    max_lines: int = 200,
) -> tuple[str, str] | None:
    """
    Return ``(relative_path, file_content)`` for the most suitable file to
    generate tests for, or ``None`` if nothing is found.

    The returned ``relative_path`` is POSIX-style and relative to
    ``workspace_dir``.

    Parameters
    ----------
    workspace_dir:
        Absolute path to the cloned repository root.
    language:
        Detected language (e.g. "python", "typescript").
    max_lines:
        Upper bound on file size. Files larger than this are skipped because
        very large files produce overly complex tests.
    """
    root = Path(workspace_dir)
    lang_lower = language.lower()
    valid_exts = _LANG_EXTENSIONS.get(lang_lower, frozenset())
    entry_signals = set(_ENTRY_SIGNALS.get(lang_lower, []))

    candidates: list[dict] = []

    for dirpath, dirnames, filenames in os.walk(root):
        # Prune ignored directories in-place so os.walk won't descend into them.
        dirnames[:] = [d for d in dirnames if d not in _SKIP_DIRS]

        for filename in filenames:
            full_path = Path(dirpath) / filename
            rel_path = full_path.relative_to(root).as_posix()

            # Must match language extension
            if valid_exts and full_path.suffix not in valid_exts:
                continue

            # Skip test files
            if _is_test_file(rel_path):
                continue

            # Skip known config-only filenames
            if filename in _CONFIG_ONLY_FILES:
                continue

            try:
                content = full_path.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue

            line_count = content.count("\n")

            # Too small to be meaningful (< 5 meaningful lines)
            if line_count < 4:
                continue

            # Too large for a focused test
            if line_count > max_lines:
                continue

            # Skip auto-generated files
            if _is_generated(content):
                continue

            is_entry = filename in entry_signals
            candidates.append({
                "rel_path": rel_path,
                "content":  content,
                "lines":    line_count,
                # Priority 0 = entry point (preferred), 1 = any other file
                "priority": 0 if is_entry else 1,
            })

    if not candidates:
        logger.warning(
            "find_best_file_to_test: no suitable %s source file found "
            "(max_lines=%d, workspace=%s)",
            language, max_lines, workspace_dir,
        )
        return None

    # Sort: entry points first, then by line count descending (more content = richer tests)
    candidates.sort(key=lambda c: (c["priority"], -c["lines"]))
    best = candidates[0]

    logger.info(
        "Best file to test: %s (%d lines, priority=%d)",
        best["rel_path"], best["lines"], best["priority"],
    )
    return best["rel_path"], best["content"]
